In [22]:
import numpy as np

In [23]:
revenue = np.array([[180, 200, 220],
                     [24, 36, 40],
                     [12, 18, 20]])

In [24]:
expenses = np.array([[80, 90, 100],
                     [10, 16, 20],
                     [8,10,10]])

#matrix substraction

In [25]:
profite =revenue-expenses

In [26]:
profite

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [27]:
unite = np.array([[1,3,4],
                  [4,56,8],
                  [67,23,90]])

In [28]:
cost = revenue*unite

In [29]:
cost

array([[ 180,  600,  880],
       [  96, 2016,  320],
       [ 804,  414, 1800]])

In [30]:
unite2 = np.array([56, 45, 89])

In [31]:
cost2 = revenue* unite2

In [32]:
cost2

array([[10080,  9000, 19580],
       [ 1344,  1620,  3560],
       [  672,   810,  1780]])

In [33]:
np.dot(unite , revenue)

array([[  300,   380,   420],
       [ 2160,  2960,  3280],
       [13692, 15848, 17460]])