In [1]:
import numpy as np
a = np.array([5,6,7])
a

array([5, 6, 7])

In [2]:
a[0]

5

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [4]:
a.itemsize

4

In [5]:
dt = np.dtype('int32')

In [6]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [7]:
a.shape

(3, 2)

In [8]:
a = np.array([[1,2],[3,4],[5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

a = np.array([[1,2],[3,4],[5,6]], dtype=int)
a

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.arange(1,5)

array([1, 2, 3, 4])

In [12]:
np.linspace(1,4,50)

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [13]:
a.shape

(3, 2)

In [14]:
a.reshape

<function ndarray.reshape>

In [15]:
a.reshape(3,2)

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

numpy function 

In [16]:
a.min
a.min()

(1+0j)

In [17]:
a.min()

(1+0j)

In [18]:
a.max()

(6+0j)

In [19]:
a.sum()

(21+0j)

In [20]:
a.sum(axis=0)

array([ 9.+0.j, 12.+0.j])

In [21]:
a.sum(axis=1)

array([ 3.+0.j,  7.+0.j, 11.+0.j])

In [22]:
np.sqrt(a)

array([[1.        +0.j, 1.41421356+0.j],
       [1.73205081+0.j, 2.        +0.j],
       [2.23606798+0.j, 2.44948974+0.j]])

In [23]:
a = np.array([[1,2],[3,4],[5,6]], dtype=int)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])


In [25]:
x+y
x*y
x/y


array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])